const players = [
    {
      name: 'Lionel Messi',
      team: 'Paris Saint-Germain',
      nationality: 'Argentina',
      jerseyNumber: 30,
      age: 34,
      imageUrl: 'https://media.gettyimages.com/id/1442809576/photo/lionel-messi-of-argentina-poses-during-the-official-fifa-world-cup-qatar-2022-portrait.jpg?s=612x612&w=0&k=20&c=EPHrEj6oYAsr2PEKLYM7HMEh3XSiXMJbo9AhAhgYGEo='
    },
    {
      name: 'Cristiano Ronaldo',
      team: 'Manchester United',
      nationality: 'Portugal',
      jerseyNumber: 7,
      age: 36,
      imageUrl: 'https://media.gettyimages.com/id/1454029167/photo/cristiano-ronaldo-smiles-as-he-is-unveiled-as-an-al-nassr-player-at-mrsool-park-stadium-on.jpg?s=612x612&w=0&k=20&c=M3Gf2V64CamE0mD6gpeH9Qb3ohGEm2Ou5xc5ZH4fLmc=',
    },
    {
      name: 'Neymar Jr',
      team: 'Paris Saint-Germain',
      nationality: 'Brazil',
      jerseyNumber: 10,
      age: 29,
      imageUrl: 'https://media.gettyimages.com/id/1430806181/photo/sl-benfica-v-paris-saint-germain-group-h-uefa-champions-league.jpg?s=612x612&w=gi&k=20&c=OxvygSBGsw9W2LIICBDIeXMFi3K7jSwEGneEdNjexEo=',
    },
    {
      name: 'Kevin De Bruyne',
      team: 'Manchester City',
      nationality: 'Belgium',
      jerseyNumber: 17,
      age: 30,
      imageUrl: 'https://media.gettyimages.com/id/1207355415/photo/manchester-city-v-west-ham-united-premier-league.jpg?s=612x612&w=gi&k=20&c=H7_f3fv1MNU5Wp_9z8F_IoFU5s5k2KnOELh92nkcEUk=',
    },
    {
      name: 'Mohamed Salah',
      team: 'Liverpool',
      nationality: 'Egypt',
      jerseyNumber: 11,
      age: 29,
      imageUrl: 'https://media.gettyimages.com/id/1203388983/photo/liverpool-fc-v-southampton-fc-premier-league.jpg?s=612x612&w=gi&k=20&c=QnjkofPSIIKpPC7AP0Vu-YDyNfdbWGtl1A7seVHxEMY=',
    },
    {
      name: 'Robert Lewandowski',
      team: 'Bayern Munich',
      nationality: 'Poland',
      jerseyNumber: 9,
      age: 33,
      imageUrl: 'https://media.gettyimages.com/id/1254307925/photo/bayer-04-leverkusen-v-fc-bayern-muenchen-dfb-cup-final.jpg?s=612x612&w=gi&k=20&c=3HoI9QodUTCXF0tuZLbgb5t7j0bUuIBYHBJDPfgzBAA=',
    },
    {
      name: 'Kylian Mbappé',
      team: 'Paris Saint-Germain',
      nationality: 'France',
      jerseyNumber: 7,
      age: 23,
      imageUrl: 'https://media.gettyimages.com/id/1383857177/photo/real-madrid-v-paris-saint-germain-round-of-sixteen-leg-two-uefa-champions-league.jpg?s=612x612&w=gi&k=20&c=Kn77e4kj91i5YxbGCAwZqwA4n18ZFxmKxWZWGSaXpS4=',
    },
    {
      name: 'Harry Kane',
      team: 'Tottenham Hotspur',
      nationality: 'England',
      jerseyNumber: 10,
      age: 28,
      imageUrl: 'https://media.gettyimages.com/id/1327533561/photo/england-v-denmark-uefa-euro-2020-semi-final.jpg?s=612x612&w=gi&k=20&c=N097ODKCZVX9o-bNzWGi2j2VwTjLf9Tf5V94ydAdxSU=',
    },
    {
      name: 'Sergio Ramos',
      team: 'Paris Saint-Germain',
      nationality: 'Spain',
      jerseyNumber: 4,
      age: 35,
      imageUrl: 'https://media.gettyimages.com/id/1327603864/photo/paris-saint-germain-unveil-new-signing-sergio-ramos.jpg?s=612x612&w=gi&k=20&c=edyZkUjUtzMQpKW0XzGkGfFGdA4LbmTX_fKQPLshsSE=',
    },
    {
      name: 'Manuel Neuer',
      team: 'Bayern Munich',
      nationality: 'Germany',
      jerseyNumber: 1,
      age: 35,
      imageUrl: 'https://media.gettyimages.com/id/1431780081/photo/borussia-dortmund-v-fc-bayern-m%C3%BCnchen-bundesliga.jpg?s=612x612&w=gi&k=20&c=l9mrL9T4a-nG66YTjqeV5-R_4Edmr3h_HJGYLu_rcjc=',
    },
  ];
  
  export default players;
  